# Customizing Docker image to install some niceties like starship prompt and fish config.
image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      mkdir -p /workspace/.fish
      mkdir -p ~/.local/share/
  - command: ln -s /workspace/.fish ~/.local/share/fish