# Customizing Docker image to install some niceties like starship prompt and fish config.
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    init: >
      mkdir -p /workspace/.fish
    command: mkdir -p ~/.local/share && ln -s /workspace/.fish ~/.local/share/fish