# Customizing Docker image to install some niceties like starship prompt and fish config.
image:
  file: .gitpod.Dockerfile

tasks:
  - init: > 
      # Sets up fish w/ persistent history in workspace.
      sh ./.gitpod-scripts/fish-install.sh
      # Regular npm install.
      npm install
